In [247]:
import torch
import numpy as np

In [259]:
def calc_2_moments(tensor):
    tensor.squeeze_()
    c, h, w = tensor.shape
    n = h * w    
    flat_array = tensor.view(c, n)
    
    mu = flat_array.mean(dim=1).reshape(3, -1)
    cov = torch.sub(flat_array, mu)
    cov = torch.div(torch.matmul(cov, cov.t()), n)    
    
    return mu, cov

In [260]:
tensor = torch.randint(low = 1, high = 4, size = [3,2,2])
tensor = tensor.float()
calc_2_moments(tensor)

(tensor([[2.2500],
         [1.7500],
         [2.0000]]), tensor([[ 0.1875, -0.1875,  0.2500],
         [-0.1875,  0.6875,  0.2500],
         [ 0.2500,  0.2500,  1.0000]]))

In [252]:
def calc_2_moments(tensor):
    chans = tensor.shape[1]
    tensor = tensor.view(1, chans, -1)
    n = tensor.shape[2]
    
    mu = tensor.mean(2)
    tensor = (tensor - mu[:,:,None]).squeeze(0)
    cov = torch.mm(tensor, tensor.t()) / float(n)
    
    return mu, cov

In [261]:
calc_2_moments(tensor.squeeze())

(tensor([[2.2500],
         [1.7500],
         [2.0000]]), tensor([[ 0.1875, -0.1875,  0.2500],
         [-0.1875,  0.6875,  0.2500],
         [ 0.2500,  0.2500,  1.0000]]))

In [245]:
tensor = torch.randint(low = 1, high = 4, size = [3,2,2])
tensor = tensor.float()
calf_2_moments(tensor)

tensor([[[3., 3.],
         [3., 1.]],

        [[3., 1.],
         [3., 3.]],

        [[1., 3.],
         [3., 3.]]])

In [246]:
calf_2_moments(tensor)


tensor([[3., 3., 3., 1.],
        [3., 1., 3., 3.],
        [1., 3., 3., 3.]])
tensor([[2.5000],
        [2.5000],
        [2.5000]])
tensor([[ 3., -1., -1.],
        [-1.,  3., -1.],
        [-1., -1.,  3.]])
tensor([[ 0.7500, -0.2500, -0.2500],
        [-0.2500,  0.7500, -0.2500],
        [-0.2500, -0.2500,  0.7500]])


In [176]:
def calc_waterstein(content, style):
    
    mu_content, cov_content = content
    mu_style, cov_style = style
    
    dis = torch.matmul(torch.sub(mu_content - mu_style), torch.sub(mu_content - mu_style))
    cov

torch.Size([12, 24])

In [123]:
# 1/n * summe(xi) for each layer
# 
# mean = (tensor[0], tensor[1], tensor[2])
mean = tensor.mean(dim=[1,-1])
# 1/n-1 summe(|xi-mean|*|xi-mean|)
n = (float(1)/float((224*224)-1))
# Ex = torch.mul(n, (torch.sum(torch.sqrt(torch.mul(torch.sub(tensor, mean), torch.sub(tensor, mean))))))
# Ex
c = calc_sigma(tensor)
# torch.mul(c, n)
c

tensor
tensor([[[1., 1.],
         [3., 2.]],

        [[3., 3.],
         [2., 3.]],

        [[2., 2.],
         [2., 3.]],

        [[3., 2.],
         [1., 2.]]])
mean
tensor([[1.7500],
        [2.7500],
        [2.2500],
        [2.0000]])
sigma after sub
tensor([[-0.7500, -0.7500,  1.2500,  0.2500],
        [ 0.2500,  0.2500, -0.7500,  0.2500],
        [-0.2500, -0.2500, -0.2500,  0.7500],
        [ 1.0000,  0.0000, -1.0000,  0.0000]])
sigma transposed
tensor([[[-0.7500,  1.2500],
         [-0.7500,  0.2500]],

        [[ 0.2500, -0.7500],
         [ 0.2500,  0.2500]],

        [[-0.2500, -0.2500],
         [-0.2500,  0.7500]],

        [[ 1.0000, -1.0000],
         [ 0.0000,  0.0000]]])
after matrix multiplication
tensor([[[ 1.1250, -1.1250],
         [-1.1250,  1.6250]],

        [[ 0.1250, -0.1250],
         [-0.1250,  0.6250]],

        [[ 0.1250, -0.1250],
         [-0.1250,  0.6250]],

        [[ 1.0000, -1.0000],
         [-1.0000,  1.0000]]])
tensor([[0.0000, 0.5000],
   

tensor([[0.0000, 0.5000],
        [0.0000, 0.5000],
        [0.0000, 0.5000],
        [0.0000, 0.0000]])

In [ ]:
tensor.dtype

In [ ]:
ts = torch.randn([2,2])
print(ts)
ts.res

In [ ]:

tensor.permute(-3, 2, 1)

tensor.shape

In [ ]:
torch.sub(tensor.view(3, 224*224), mean.reshape(3,-1))

In [ ]:
mean_t = torch.Tensor()
mean_t.new_full(tensor.shape, 1)

In [ ]:
tensor.shape[0]

In [ ]:
torch.sub(tensor, torch.mean(tensor))

In [ ]:
torch.var(torch.sub(tensor, torch.mean(tensor)), unbiased=False)

In [ ]:
tensor.squeeze().size()

In [ ]:
tensor.view(224,224)

In [ ]:
tensor[0]

In [ ]:
tensor[1]

In [ ]:
tensor[2]